{"name": "Verify scans are returned correctly for a valid chatbot ID -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <SCAN_IN_PROGRESS> to be equal to <REPORT_GENERATED>, but was not.\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Get_all_scans_of_a_chatbot_by_chatbotID.py\", line 73, in step_impl\n    assert_that(status).is_equal_to(\"REPORT_GENERATED\")\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\base.py\", line 126, in is_equal_to\n    self.error('Expected <%s> to be equal to <%s>, but was not.' % (self.val, other))\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n"}, "steps": [{"name": "Given User sends GET request to fetch scans for chatbot ID \"89ebd370-38bb-43e5-9956-5c8cda370b9c\"", "status": "passed", "start": 1757682266655, "stop": 1757682270931}, {"name": "When the user receives the scans response", "status": "passed", "start": 1757682270931, "stop": 1757682270933}, {"name": "Then the status code returned should be 200 for successful scans retrieval", "status": "passed", "start": 1757682270935, "stop": 1757682270936}, {"name": "And the response should contain a list of scans", "status": "passed", "start": 1757682270937, "stop": 1757682270941}, {"name": "And each scan should contain a valid \"scan_id\" of length 36", "status": "passed", "start": 1757682270942, "stop": 1757682270944}, {"name": "And each scan should contain a \"creation_timestamp\" in ISO 8601 format", "status": "passed", "start": 1757682270944, "stop": 1757682270946}, {"name": "And each scan should have a \"status\" equal to \"REPORT_GENERATED\"", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <SCAN_IN_PROGRESS> to be equal to <REPORT_GENERATED>, but was not.\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Get_all_scans_of_a_chatbot_by_chatbotID.py\", line 73, in step_impl\n    assert_that(status).is_equal_to(\"REPORT_GENERATED\")\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\base.py\", line 126, in is_equal_to\n    self.error('Expected <%s> to be equal to <%s>, but was not.' % (self.val, other))\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n"}, "start": 1757682270946, "stop": 1757682270959}], "parameters": [{"name": "chatbot_id", "value": "89ebd370-38bb-43e5-9956-5c8cda370b9c"}], "start": 1757682266654, "stop": 1757682270961, "uuid": "a40f2e98-e28f-4d95-a765-efd41b495ba8", "historyId": "b9effca286996308b3291f82629baf1a", "fullName": "Get Scans by Chatbot ID using Genr3d API: Verify scans are returned correctly for a valid chatbot ID", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Test"}, {"name": "feature", "value": "Get Scans by Chatbot ID using Genr3d API"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "titlePath": ["features", "Get Scans by Chatbot ID using Genr3d API"]}