{"name": "Verify scan is initiated successfully with valid chatbot and environment IDs -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <400> to be equal to <200>, but was not.\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Initiate_a_new_scan_for_a_chatbot.py\", line 48, in step_impl\n    assert_that(context.response.status_code).is_equal_to(200)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\base.py\", line 126, in is_equal_to\n    self.error('Expected <%s> to be equal to <%s>, but was not.' % (self.val, other))\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n"}, "steps": [{"name": "Given User sends POST request to initiate a scan with chatbot \"c1ca42ab-a401-45b0-a945-d9cd549d7590\" and environment \"aae0a1b6-fafe-40af-ab20-87934343521f\"", "status": "passed", "start": 1757682276070, "stop": 1757682281500}, {"name": "When the user receives the scan initiation response", "status": "passed", "start": 1757682281501, "stop": 1757682281503}, {"name": "Then the status code returned should be 200 for successful scan initiation", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <400> to be equal to <200>, but was not.\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Initiate_a_new_scan_for_a_chatbot.py\", line 48, in step_impl\n    assert_that(context.response.status_code).is_equal_to(200)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\base.py\", line 126, in is_equal_to\n    self.error('Expected <%s> to be equal to <%s>, but was not.' % (self.val, other))\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n"}, "start": 1757682281504, "stop": 1757682281509}, {"name": "And the response should contain a \"scan_id\"", "status": "skipped", "start": 1757682281516, "stop": 1757682281516}, {"name": "And the response status should be \"SCAN_REQUESTED\"", "status": "skipped", "start": 1757682281516, "stop": 1757682281516}], "parameters": [{"name": "target_chatbot", "value": "c1ca42ab-a401-45b0-a945-d9cd549d7590"}, {"name": "target_env", "value": "aae0a1b6-fafe-40af-ab20-87934343521f"}], "start": 1757682276048, "stop": 1757682281516, "uuid": "b399ea22-1344-4f36-9f83-aa8931f8dc10", "historyId": "974886f2268df271bcb0d104c9bf9698", "fullName": "Initiate Scan using Genr3d API: Verify scan is initiated successfully with valid chatbot and environment IDs", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Test"}, {"name": "feature", "value": "Initiate Scan using Genr3d API"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "titlePath": ["features", "Initiate Scan using Genr3d API"]}